export const FETCH_BLOGS = 'FETCH_BLOGS';
export const VIEW_BLOG = 'VIEW_BLOG';
export const ADD_BLOG = 'ADD_BLOG';
export const EDIT_BLOG = 'EDIT_BLOG';
export const DELETE_BLOG = 'DELETE_BLOG';

export const CHANGE_PAGE = 'CHANGE_PAGE';

export const REGISTER_USER_ACCOUNT = 'REGISTER_USER_ACCOUNT';
export const LOGIN_USER_ACCOUNT = 'LOGIN_USER_ACCOUNT';
export const DELETE_USER_ACCOUNT = 'DELETE_USER_ACCOUNT';
export const FOLLOW_USER_ACCOUNT = 'FOLLOW_USER_ACCOUNT';
export const UNFOLLOW_USER_ACCOUNT = 'UNFOLLOW_USER_ACCOUNT';
